version: '3.9'

services:
  api_gateway:
    build:
      context: ./api_gateway
    container_name: api_gateway
    ports:
      - "8080:80"
    networks:
      - clinic_network
    depends_on:
      - postgres_api_gateway

  servicio_citas:
    build:
      context: ./servicio_citas
    container_name: servicio_citas
    ports:
      - "8081:5000"
    depends_on:
      - postgres_citas
    networks:
      - clinic_network

  servicio_pacientes:
    build:
      context: ./servicio_pacientes
    container_name: servicio_pacientes
    ports:
      - "8082:5000"
    depends_on:
      - postgres_pacientes
    networks:
      - clinic_network

  servicio_doctores:
    build:
      context: ./servicio_doctores
    container_name: servicio_doctores
    ports:
      - "8083:5000"
    depends_on:
      - postgres_doctores
    networks:
      - clinic_network

  servicio_calendario:
    build:
      context: ./servicio_calendario
    container_name: servicio_calendario
    ports:
      - "8084:5000"
    depends_on:
      - postgres_calendario
    networks:
      - clinic_network

  postgres_api_gateway:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: api_gateway_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_api_gateway_data:/var/lib/postgresql/data

  postgres_citas:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: citas_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_citas_data:/var/lib/postgresql/data

  postgres_pacientes:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: pacientes_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_pacientes_data:/var/lib/postgresql/data

  postgres_doctores:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: doctores_db
    ports:
      - "5437:5432"
    volumes:
      - postgres_doctores_data:/var/lib/postgresql/data

  postgres_calendario:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: calendario_db
    ports:
      - "5438:5432"
    volumes:
      - postgres_calendario_data:/var/lib/postgresql/data

networks:
  clinic_network:

volumes:
  postgres_api_gateway_data:
  postgres_citas_data:
  postgres_pacientes_data:
  postgres_doctores_data:
  postgres_calendario_data:
